### ISSUE TITLE
Using protoc-gen-es with protoc

### ISSUE THREAD

**Issue by itzhak-ira** [bufbuild/connect-web#219]
**Describe the bug**
I'm attempting to use the code generation with `protoc` (docs claim the plugin should work just as it does with buf) but I can't seem to get protoc to recognize the `--target=ts` flag (`Unknown flag: --target`)

**To Reproduce**

1) yarn add --dev @bufbuild/protoc-gen-connect-web @bufbuild/protoc-gen-es
2) yarn add @bufbuild/connect-web @bufbuild/protobuf
3) add the executable to `PATH` (.zshrc):
```
#Environment Settings
export NODEMODULES_PATH=$HOME/path/to/node_modules/.bin
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$NODEMODULES_PATH
```
4) check binary has been added to `PATH` successfully:
```
$cmd: protoc-gen-es --version
    protoc-gen-es v0.0.10
```
5) execute `protoc`:
```
protoc --proto_path=protos \
--go_out=. --go_opt=module=github.com/repo/project \
--go-grpc_out=. --go-grpc_opt=module=github.com/repo/project \
--grpc-gateway_out=. --grpc-gateway_opt=module=github.com/repo/project \
--target=ts \
protos/*.proto
```
result: `Unknown flag: --target`

**Environment (please complete the following information):**
- @bufbuild/protoc-gen-connect-web: ^0.1.0
- @bufbuild/protoc-gen-es: ^0.0.10
- @bufbuild/connect-web version: ^0.1.0
- @bufbuild/protobuf version: ^0.0.10

**Comment by bufdev** [comment]
You aren't invoking the `protoc-gen-es` plugin in your `protoc` invocation. You need to be calling `protoc --es_out=. --es_opt=target=ts ...`

**Comment by itzhak-ira** [comment]
@bufdev ah, of course. Thanks.

**Comment by timostamm** [comment]
You can also find a full example for connect-web [here](https://github.com/bufbuild/connect-web/tree/main/packages/example#generate-code-yourself). (Note that our example declares the plugin with `--plugin=`. You do not need to do that if you already have it on your `$PATH`.)

You might also find our documentation for the buf CLI helpful, especially the page [Replace protoc with buf](https://docs.buf.build/how-to/replace-protoc-with-buf). It shows how plugins and import paths are declared in `buf` vs `protoc`.

Thanks for giving it a try, we appreciate the feedback!

**Comment by itzhak-ira** [comment]
@timostamm @bufdev thanks - unrelated (and without wanting to open another issue item), is there anyway currently to tell compiler to export the `_connectweb.ts` and `_pb.ts` files into separate folders while having the generated `_connectweb.ts` files import the necessary types from `_pb.ts` files correctly?

```
├── Services
│   └── user_connectweb.ts
└── Types
    └── user_pb.ts
```
Also - is there a way to configure the filenames to match typical JS/TS file naming conventions and use PascalCase rather than snake_case? i.e:

```
user_connectweb.ts > UserConnectWeb.ts
user_pb.ts > UserPb.ts
```

... would love to just be able to customize the generated filenames altogether.

Great tool btw, amazing for productivity and efficiency!

**Comment by timostamm** [comment]
For file names, we simply use the full path of the protobuf source, and replace the extension with `_connectweb.ts` / `_pb.ts`. This is predictable, and trivial to implement in other tooling we might want to interoperate with. We deliberately want to keep it simple for a start. But that doesn't mean we can't pivot in the future. I've taken a note about this - thanks for the input!

Regarding generating into separate folders: We are working on a feature to generate connect-web and protobuf-es output into two separate packages in [remote generation](https://docs.buf.build/bsr/remote-generation/js). I think this might end up doing pretty much what you want. This will probably land within the next weeks - stay tuned!
