### ISSUE TITLE
Exceptions thrown from ASP.NET gRPC Service getting converted to "premature eof" error.

### ISSUE THREAD

**Issue by adambritto-mts** [bufbuild/connect-web#238]
**Describe the bug**

I am using gRPC from an ASP.NET backend server, talking to a VueJS frontend client, running in Edge and Chrome (chromium).

When throwing an exception from within a gRPC service call, the exception appears to be misprocessed when received within the response header on the client.

```
// C# ASP.NET 

public override Task<Foo> Create(Foo request, ServerCallContext context)
{
    if (alreadyExists(request))
    {
        throw new RpcException(new Status(StatusCode.AlreadyExists, "Foo already exists"));
    }

    // Create Foo
    return Task.FromResult(request);
}
```

On the client side, this results in the callback/promise rejection containing a "premature eof" error.

The source of the error is within [grpc-web-transport](https://github.com/bufbuild/connect-web/blob/e75cccbcd99de5d7d0b08a0a4b6eba6ff028fa57/packages/connect-web/src/grpc-web-transport.ts#L149).

I believe the expectation is that the [header will contain the status code](https://github.com/bufbuild/connect-web/blob/e75cccbcd99de5d7d0b08a0a4b6eba6ff028fa57/packages/connect-web/src/grpc-web-transport.ts#L370), but upon testing, the only thing present in the header at the time is `0 content-length`.

Interestingly, after the operation is complete, upon inspecting the network traffic in developer tools, both `grpc-status` and `grpc-message` are present and with the values from the exception thrown from C#.

**Environment (please complete the following information):**
- @bufbuild/connect-web version: 0.1.0
- Framework and version: vue@3.2.37, nuxt@3.0.0-rc.8
- Browser and version: Microsoft Edge 104.0.1293.63, Google Chrome 104.0.5112.102

**Additional context**
This may not be a bug, but rather some misconfiguration on the C# side which is causing the response to be processed incorrectly, but at this stage I am running out of ideas.

**gRPC response from GRPCUI**
![grpc response](https://user-images.githubusercontent.com/111340962/186113956-0a6c8adf-0a7e-496e-a610-dcc3dde7c134.PNG)

**Response header after request has completed**
![Response Headers](https://user-images.githubusercontent.com/111340962/186113964-50776b75-d2db-49f5-a6d8-d16166486e26.PNG)

**Output during breakpoint debugging, at the point of `grpc-web-transport` looking for the `grpc-status` header**
![Debug output](https://user-images.githubusercontent.com/111340962/186114281-8cb4f9a1-fc16-4390-908d-42165e2fc7e8.PNG)

**Comment by timostamm** [comment]
Hey Adam, thanks for the detailed report!

Looking at the response headers, the content-type is as expected, and there is a `grpc-status: 6`. This means the following line should pick up code 6, and raise a `ConnectError` with `Code.AlreadyExists`:

https://github.com/bufbuild/connect-web/blob/e75cccbcd99de5d7d0b08a0a4b6eba6ff028fa57/packages/connect-web/src/grpc-web-transport.ts#L137

But according to the debug log, the header is not present. This leads me to believe that this is a CORS issue. You server needs to explicitly safelist the `Grpc-Status` and `Grpc-Message` fields via the `Access-Control-Expose-Headers` field.

You can do so in .NET with a CORS middleware: https://docs.microsoft.com/en-us/aspnet/core/grpc/grpcweb?view=aspnetcore-6.0#grpc-web-and-cors

Let us know if that fixes the issue.

**Comment by adambritto-mts** [comment]
Hi Timo,

You were completely correct! I had suspicions it may have been CORS related, but had it misconfigured, and sure enough those headers weren't being exposed. 

The problem is now solved. Thank you very much for the help!

**Comment by adambritto-mts** [comment]
May I request a footnote be added to the documentation, to help out the next poor developer that thinks it's a good idea to start digging through source code to solve this fairly simple problem? ;)
