### ISSUE TITLE
More info on using the generated definitions?

### ISSUE THREAD

**Issue by boan-anbo** [bufbuild/connect-web#291]
Been using connect-web for some time, it's sooo good compared to the past JS/TS generators I've used. Thanks so much for the work!

I was wondering if the documentation could add a few words on how best to use the generated definitions.

For example, what are the intended uses for `PartialMessage<T>` and `PlainMessage<T>`?  What's the best practice for class conversions and initialization? I ask because, for example, the default constructor's parameter PartialMessage has insufficient IDE support and shows no auto-complete when initializing. The `FieldList` helps with type-checking but it's not too clear if it's intended for the users or for internal use.

The documentation already covered how to convert to/from JSON and binary; a few more documentation examples on which interface/class/functions to use for type-checking during conversions to/from other user types will be very much appreciated!

**Comment by timostamm** [comment]
Hey @boan-anbo, 

I think something is off with your IDE. The TypeScript language service should absolutely be able to provide auto-complete and suggestions:

<img width="485" alt="Screen Shot 2022-10-10 at 13 08 20" src="https://user-images.githubusercontent.com/4289451/194854922-c64db964-c7c2-46f8-b936-d3be9c8946a2.png">

Maybe you need to update TypeScript, or some part of your IDE? This should definitely work!

Thanks for your questions regarding initialization! If you want to create a new instance of a message, you should always use `new`, and pass the properties where you want to provide a value. This makes sure that other properties - for example map fields, repeated fields and scalar fields - always have their default value. You can find more information [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#constructing-messages) and [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#default-field-values).

We use `PartialMessage<T>` for the initializer object of constructors - it simply makes all properties optional. In your code, you should only use `PartialMessage<T>` if you provide an API for other users, and want to give them the most flexibility for passing in data. 

`PlainMessage<T>` is an exact representation of just the fields of a message, without any of its methods. You can find more information [here](https://github.com/bufbuild/protobuf-es/blob/main/docs/runtime_api.md#plainmessage). This type _can_ be useful in you business logic, if you don't care about the class methods for serialization, and don't need `instanceof`. Note that we are going to improve this part soon, see https://github.com/bufbuild/protobuf-es/issues/230#issuecomment-1257544673.

I am sorry our connect.build documentation wasn't more helpful. I think we do have some hopefully helpful [documentation on protobuf-es](https://github.com/bufbuild/protobuf-es/tree/main/docs), but we definitely need to integrate it better with connect.build. I've bumped the priority of our internal ticket for this. Thanks for your input!

**Comment by timostamm** [comment]
Closing this. Please feel free to reopen in case I was missing something!
