### ISSUE TITLE
Improve documentation on handling Errors

### ISSUE THREAD

**Issue by easyCZ** [bufbuild/connect-web#312]
**Is your feature request related to a problem? Please describe.**
In the current documentation or examples, errors from calls are mostly unhandled. 

**Describe the solution you'd like**
It would be useful to extend the documentation on how to handle Errors.

In particular, showing how to:
* Check the Error Code client-side
* Extract the code & message from the response
* For typescript, assert that the error is a `ConnectError` to receive hints on fields to access
* Extract error details

That aside, really loving `connect-web`, and the ecosystem you've built on top of gRPC.

**Comment by timostamm** [comment]
Thanks to the feedback, Milan!

The documentation page [connect.build](https://connect.build/docs/web/errors) has examples for handling errors and accessing error details. We're going to update the READMEs to make that a bit more discoverable in https://github.com/bufbuild/connect-web/pull/314.

Do you feel like you would want more concrete, runnable examples?

**Comment by easyCZ** [comment]
Ah, it does contain it, including the details. My bad, I must have missed that in the docs.

This works for me, and likely others. Thanks!

**Comment by timostamm** [comment]
If it's easy to miss, that's on us, thanks again for the feedback :)
